export const REQUEST_METHOD = "REQUEST_METHOD";

export const SUCCESS_CATEGORY_METHOD = "SUCCESS_CATEGORY_METHOD";

export const SUCCESS_PRODUCT_METHOD = "SUCCESS_PRODUCT_METHOD";

export const SUCCESS_FILTER_METHOD = "SUCCESS_FILTER_METHOD";

export const SUCCESS_SINGLE_PRODUCT_METHOD = "SUCCESS_SINGLEPRODUCT_METHOD";

export const FAILURE_METHOD = "FAILURE_METHOD";
